### ISSUE TITLE
Validation required when same url is saved

### ISSUE THREAD

**Issue by zhiyann** [bumfuzzled93/UrlShortener#12]
Is this a bug?

What if somehow saveUrl failed but in the response, it is always returning OK.
    @PostMapping("/url")
   ...
        urlService.saveUrl(actualUrl, timeHours);
        return new ResponseEntity(HttpStatus.OK);

**Comment by bumfuzzled93** [comment]
Yes. if the url already exist the creation should fail. We can add this as a bug to be fixed

**Comment by zhiyann** [comment]
i have created a boolean to test the saveurl in the same pr
