### ISSUE TITLE
QR Module

### ISSUE THREAD

**Issue by bumfuzzled93** [bumfuzzled93/UrlShortener#5]
We need to add the capability to generate QR codes with the shortened QR.
Basically whenever a shorten url is generated, the qr code should be generated too and a link to the qr should be provided with the url object

@zhiyann 
You can refer to this https://github.com/zxing/zxing

**Comment by zhiyann** [comment]
Approach
1) Change the Url Class to accept a link field
2) Include dependency in pom.xml

@bumfuzzled93

**Comment by bumfuzzled93** [comment]
@zhiyann prefer you to write an entire new package QR similar to the current Url package that we have.
This new package should have it own controller for displaying the qr code
its own service method to read and creation of qr code and tagging it to existing shorteners
Also it should have its own repository and table

**Comment by zhiyann** [comment]
created a pr for this please review

**Comment by zhiyann** [comment]
i didnt see your comment. i have created a pr. if is not okay, please reject the pr
